load("@rules_javascript//commonjs:rules.bzl", "cjs_root")
load("@rules_javascript//javascript:rules.bzl", "js_library")

package(default_visibility = ["//visibility:public"])

exports_files(["REPO.bazel"])

alias(
    name = "bazelrc",
    actual = "//tools/bazel_:preset_gen",
)

alias(
    name = "lint",
    actual = "//tools/lint",
)

js_library(
    name = "prettier_config",
    srcs = ["prettierrc.yml"],
    root = ":root",
)

alias(
    name = "refresh",
    actual = "//tools/bazel_:refresh",
)

cjs_root(
    name = "root",
    package_name = "@better-rules-javascript/root",
)

test_suite(
    name = "test",
    tests = [
        "//file/test",
    ],
)
