module(name = "bazel_util")

# Buildifier

include("//buildifier:buildifier.MODULE.bazel")

# Files

include("//tools/file:file.MODULE.bazel")

# Git

include("//tools/git:git.MODULE.bazel")

# GitHub

include("//tools/github:github.MODULE.bazel")

# Ibazel

include("//ibazel:ibazel.MODULE.bazel")

# JavaScript

bazel_dep(name = "rules_javascript", dev_dependency = True)

RULES_JAVASCRIPT_VERSION = "dc853d3b5ca1bcfab6e51573e1beb8587676323c"

archive_override(
    module_name = "rules_javascript",
    sha256 = "42147b63025b43c2cbb474b00e0cc8ebbd16600638f88a7416ea4828c972350e",
    strip_prefix = "rules_javascript-%s" % RULES_JAVASCRIPT_VERSION,
    url = "https://github.com/redoapp/rules_javascript/archive/%s.tar.gz" % RULES_JAVASCRIPT_VERSION,
)

include("//tools/javascript:javascript.MODULE.bazel")

# JSON

bazel_dep(name = "jq.bzl", version = "0.6.0")

# Pkg

bazel_dep(name = "rules_pkg", version = "1.2.0")

# Platforms

bazel_dep(name = "platforms", version = "1.0.0")

# Python

bazel_dep(name = "rules_python", version = "1.8.5")

include("//tools/python:python.MODULE.bazel")

# Shell

bazel_dep(name = "rules_shell", version = "0.6.1")

# Shell

bazel_dep(name = "rules_shell_extra")

RULES_SHELL_EXTRA_VERSION = "93090b47f81577ba4890c770effd889f61ce5d19"

archive_override(
    module_name = "rules_shell_extra",
    sha256 = "c69a83b7afefa03b21c370c2044c63c41800820f51680022604133a098e2c932",
    strip_prefix = "rules_shell_extra-%s" % RULES_SHELL_EXTRA_VERSION,
    url = "https://github.com/redoapp/rules_shell_extra/archive/%s.tar.gz" % RULES_SHELL_EXTRA_VERSION,
)

# Skylib

bazel_dep(name = "bazel_skylib", version = "1.9.0")

# JSON Schema

include("//jsonschema:jsonschema.MODULE.bazel")
