module(name = "bazel_util")

# Bazel

bazel_dep(name = "bazel_lib", version = "3.2.1")

# Buildifier

include("//buildifier:buildifier.MODULE.bazel")

# Files

include("//tools/file:file.MODULE.bazel")

# Git

include("//tools/git:git.MODULE.bazel")

# GitHub

include("//tools/github:github.MODULE.bazel")

# Ibazel

include("//ibazel:ibazel.MODULE.bazel")

# JavaScript

bazel_dep(name = "rules_javascript", dev_dependency = True)

RULES_JAVASCRIPT_VERSION = "f285258dae16b848c1de1c761cc50c8397b664d1"

archive_override(
    module_name = "rules_javascript",
    sha256 = "7b79cf59fc06977ce5c471dd65661dfb6a17630a03fcecda3c860abe1e9d4ba8",
    strip_prefix = "rules_javascript-%s" % RULES_JAVASCRIPT_VERSION,
    url = "https://github.com/redoapp/rules_javascript/archive/%s.tar.gz" % RULES_JAVASCRIPT_VERSION,
)

include("//tools/javascript:javascript.MODULE.bazel")

# JSON

bazel_dep(name = "jq.bzl", version = "0.6.0")

# Pkg

bazel_dep(name = "rules_pkg", version = "1.2.0")

# Platforms

bazel_dep(name = "platforms", version = "1.0.0")

# Python

bazel_dep(name = "rules_python", version = "1.8.5")

include("//tools/python:python.MODULE.bazel")

# Redo Tech

bazel_dep(name = "r_tools", dev_dependency = True)

R_TOOLS_VERSION = "0463cc21a11265216d5de0d9f0b6cea84411aac1"

archive_override(
    module_name = "r_tools",
    integrity = "sha256-KGyW7D6itHePuBnsIafLG2ZUfvaX5iWFMwFHepfRo8w=",
    strip_prefix = "r-tools-%s" % R_TOOLS_VERSION,
    url = "https://github.com/redoapp/r-tools/archive/%s.tar.gz" % R_TOOLS_VERSION,
)

# Shell

bazel_dep(name = "rules_shell", version = "0.6.1")

# Shell

bazel_dep(name = "rules_shell_extra")

RULES_SHELL_EXTRA_VERSION = "ef9a80e7f6d4b8303382ac64214c39cc2b3b7794"

archive_override(
    module_name = "rules_shell_extra",
    sha256 = "49c96a95dd040dfbf2d13f872a88064a8efacc9000752b25815e53581d057e6b",
    strip_prefix = "rules_shell_extra-%s" % RULES_SHELL_EXTRA_VERSION,
    url = "https://github.com/redoapp/rules_shell_extra/archive/%s.tar.gz" % RULES_SHELL_EXTRA_VERSION,
)

# Skylib

bazel_dep(name = "bazel_skylib", version = "1.9.0")

# JSON Schema

include("//jsonschema:jsonschema.MODULE.bazel")
