workspace(name = "bazel_util")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# JavaScript

JAVASCRIPT_VERSION = "1601e401446b5f954b47fb26babcaf2608db7274"

http_archive(
    name = "better_rules_javascript",
    repo_mapping = {
        "@rules_file": "@",
    },
    sha256 = "6c4affd5ae8fb4788de83bb33c02d198a9544a577b70614d084008b4426db106",
    strip_prefix = "rules_javascript-%s" % JAVASCRIPT_VERSION,
    url = "https://github.com/redoapp/rules_javascript/archive/%s.tar.gz" % JAVASCRIPT_VERSION,
)

load("//tools/javascript:workspace.bzl", "javascript_repositories")

javascript_repositories()
