http = use_extension("//http:extensions.bzl", "http", dev_dependency = True)
http.file(
    name = "bazel_util_schemastore_github_workflow",
    downloaded_file_path = "schema.json",
    url = "https://raw.githubusercontent.com/SchemaStore/schemastore/402fdd800ea211bd1b9bccb1abcda4a2ba20073c/src/schemas/json/github-workflow.json",
)
use_repo(http, schemastore_github_workflow = "bazel_util_schemastore_github_workflow")
