file = use_extension("//file:extensions.bzl", "file", dev_dependency = True)
file.files(
    name = "bazel_util_files",
    bazelrc = "tools/file/files.bazelrc",
    build = "//tools/file:files.BUILD.bazel",
    ignore_directories_manifest = "//tools/file:ignore-directories.txt",
)
use_repo(file, files = "bazel_util_files")
