load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@bazel_util//bazelrc:rules.bzl", "bazelrc_group")
load(":rules.bzl", "all_filter")

package(default_visibility = ["//visibility:public"])

exports_files([
    "deleted-packages-diff.sh.tpl",
    "deleted-packages-gen.sh.tpl",
    "find-packages-runner.sh.tpl",
])

all_filter(
    name = "all_filter",
)

bazelrc_group(
    name = "bazelrc",
    srcs = ["file.bazelrc"],
)

bzl_library(
    name = "bzl",
    srcs = glob(["**/*.bzl"]),
)
