load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
load("@bazel_util//bazelrc:rules.bzl", "bazelrc_group")
load(":rules.bzl", "pattern_filter")

package(default_visibility = ["//visibility:public"])

exports_files([
    "deleted-packages-diff.sh.tpl",
    "deleted-packages-gen.sh.tpl",
    "find-packages-runner.sh.tpl",
])

string_flag(
    name = "pattern",
    build_setting_default = "**",
)

pattern_filter(
    name = "pattern_filter",
    pattern = ":pattern",
)

bazelrc_group(
    name = "bazelrc",
    srcs = ["file.bazelrc"],
)

bzl_library(
    name = "bzl",
    srcs = glob(["**/*.bzl"]),
)
