load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "bin",
    srcs = glob(["src/**/*.py"]),
    imports = ["src"],
    legacy_create_init = False,
    main = "src/redotech/sockactivate/__main__.py",
    python_version = "3.13",
    deps = ["//python/net:lib"],
)
