load("@better_rules_javascript//npm:rules.bzl", "yarn_resolve")
load("@better_rules_javascript//prettier:rules.bzl", "configure_prettier")
load("//black:rules.bzl", "configure_black")
load("//buildifier:rules.bzl", "buildifier")
load("//generate:rules.bzl", "format", "generate", "generate_test", "multi_generate")

sh_binary(
    name = "bazelrc",
    srcs = ["bazelrc.sh"],
    data = [
        "//tools/test:bazelrc",
        "@files//packages:bazelrc",
    ],
    deps = ["@bazel_tools//tools/bash/runfiles"],
)

configure_black(
    name = "black",
    options = ["-C"],
)

format(
    name = "black_format",
    srcs = ["@files//:black_files"],
    formatter = ":black",
    strip_prefix = "/files",
)

buildifier(
    name = "buildifier",
)

format(
    name = "buildifier_format",
    srcs = ["@files//:buildifier_files"],
    formatter = "//buildifier",
    strip_prefix = "/files",
)

multi_generate(
    name = "format",
    visibility = ["//visibility:public"],
    deps = [
        ":black_format",
        ":buildifier_format",
        "//tools/github:github_workflow_validate",
        # ":prettier_format", # TODO
    ],
)

generate_test(
    name = "format_test",
    generate = ":format",
    visibility = ["//visibility:public"],
)

configure_prettier(
    name = "prettier",
    config = "prettierrc.yml",
    config_dep = "//:prettier_config",
    dep = "@npm//prettier:lib",
)

format(
    name = "prettier_format",
    srcs = ["@files//:prettier_files"],
    formatter = ":prettier",
    strip_prefix = "/files",
)

yarn_resolve(
    name = "resolve_npm",
    output = "npm_data.bzl",
)
